name: Terraform CI CD Pipeline for Deploying AZURE Resources
run-name: ${{ github.actor }} has triggered the pipeline

on:
  push:
    branches:
      - 'main'

env:
  ACLIENT_ID: ${{ secrets.CLIENT_ID }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
  TENANT_ID: ${{ secrets.TENANT_ID}}

jobs:
  build-infra:
    name: terraform-ci-cd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ./azure
      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: ./azure
      - name: Terraform Plan
        id: plan
        run: terraform plan -out main.tfplan
        working-directory: ./azure
      - name: Terraform Apply 
        id: apply
        run: terraform apply "main.tfplan"
        working-directory: ./azure